remote_theme : "manid2/lone-wolf-theme"
url: https://kumanidev.github.io
baseurl: /jekyllassignment/
title: Kumani's Life
description: Information about me, school and career
author: Kumani Riley